const str = [["avfbfbngotbongbiguhbosfbhr"], ["gdkygsodhcg"]];
console.log(str.length);
const str2 = "abcdefghijklmnopqrstuvwxyz";
console.log(str2.length);
const upe = "abcdefgh";
console.log(upe.toUpperCase());
const low = "ABCDFT";
console.log(low.toLocaleLowerCase());
console.log(low.slice(3, 4));
const trim = "      hello world       ";
console.log(trim.trim());
